framework:
    messenger:
        transports:
            event_delivery:
                dsn: 'sync://'
                retry_strategy:
                    service: App\Messenger\DeliverEventMessageRetryStrategy
            async:
                dsn: 'sync://'

            memory:
                dsn: 'in-memory://'

        routing:
            'App\Message\JobCompletedCheckMessage': memory
