framework:
    messenger:
        transports:
            callback:
                dsn: 'sync://'
                retry_strategy:
                    service: App\Messenger\CallbackMessageRetryStrategy
            async:
                dsn: 'sync://'
