framework:
    messenger:
        transports:
            event_delivery:
                dsn: 'sync://'
                retry_strategy:
                    service: App\Messenger\DeliverEventMessageRetryStrategy
            async:
                dsn: 'sync://'
