imports:
    - { resource: services/test_common.yaml }

parameters:
    compiler_source_directory: '%env(resolve:COMPILER_SOURCE_DIRECTORY)%'
    compiler_target_directory: '%env(resolve:COMPILER_TARGET_DIRECTORY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Services\TestTestMutator:
        public: true

    app.tests.services.guzzle.handler.queuing:
        class: GuzzleHttp\Handler\MockHandler

    GuzzleHttp\HandlerStack:
        factory: [ 'GuzzleHttp\HandlerStack', 'create' ]
        arguments:
            $handler: '@app.tests.services.guzzle.handler.queuing'

    App\Tests\Services\SourceFileInspector:
        public: true
        arguments:
            $path: '%compiler_source_directory%'

    App\Tests\Services\EventRecorder:
        public: true
