# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    compiler_source_directory: '%env(COMPILER_SOURCE_DIRECTORY)%'
    compiler_target_directory: '%env(COMPILER_TARGET_DIRECTORY)%'
    event_delivery_retry_limit: '%env(int:EVENT_DELIVERY_RETRY_LIMIT)%'
    job_timeout_check_period_ms: '%env(JOB_TIMEOUT_CHECK_PERIOD_MS)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Model/'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Services\SourceFileStore:
        arguments:
            $path: '%compiler_source_directory%'

    App\Services\TestSerializer:
        arguments:
            $compilerSourceDirectory: '%compiler_source_directory%'
            $compilerTargetDirectory: '%compiler_target_directory%'

    App\Services\SourcePathFinder:
        arguments:
            $compilerSourceDirectory: '%compiler_source_directory%'

    App\Services\TestPathMutator:
        arguments:
            $compilerSourceDirectory: '%compiler_source_directory%'

    webignition\TcpCliProxyClient\HandlerFactory:
        class: webignition\TcpCliProxyClient\HandlerFactory

    app.services.compiler-client:
        class: webignition\TcpCliProxyClient\Client
        factory: [ 'webignition\TcpCliProxyClient\Client', 'createFromHostAndPort' ]
        arguments:
            $host: '%env(COMPILER_HOST)%'
            $port: '%env(COMPILER_PORT)%'

    app.services.delegator-client:
        class: webignition\TcpCliProxyClient\Client
        factory: [ 'webignition\TcpCliProxyClient\Client', 'createFromHostAndPort' ]
        arguments:
            $host: '%env(DELEGATOR_HOST)%'
            $port: '%env(DELEGATOR_PORT)%'

    App\Services\TestExecutor:
        arguments:
            $delegatorClient: '@app.services.delegator-client'

    Symfony\Component\Yaml\Parser:
        class: Symfony\Component\Yaml\Parser

    App\Services\Compiler:
        arguments:
            $client: '@app.services.compiler-client'
            $compilerSourceDirectory: '%env(COMPILER_SOURCE_DIRECTORY)%'
            $compilerTargetDirectory: '%env(COMPILER_TARGET_DIRECTORY)%'

    Psr\Http\Client\ClientInterface:
        class: GuzzleHttp\Client

    App\Services\WorkerEventFactory\:
        resource: '../src/Services/WorkerEventFactory/'
        tags: ['foo.factory']

    App\Services\WorkerEventFactory:
        arguments:
            $handlers: !tagged_iterator foo.factory

    webignition\YamlDocumentGenerator\YamlGenerator:
        class: webignition\YamlDocumentGenerator\YamlGenerator

    Symfony\Component\Yaml\Dumper: ~

    App\MessageHandler\TimeoutCheckHandler:
        tags: [messenger.message_handler]

    App\MessageDispatcher\TimeoutCheckMessageDispatcher:
        arguments:
            $checkPeriodInMilliseconds: '%job_timeout_check_period_ms%'

    app.messenger.retry_strategy.callback.multiplier:
        class: Symfony\Component\Messenger\Retry\MultiplierRetryStrategy
        arguments:
            $maxRetries: '%event_delivery_retry_limit%'
            $delayMilliseconds: 1000
            $multiplier: 2
            $maxDelayMilliseconds: 0

    App\Messenger\CallbackMessageRetryStrategy:
        arguments:
            $multiplierRetryStrategy: '@app.messenger.retry_strategy.callback.multiplier'

    webignition\YamlDocumentSetParser\Parser: ~

    SmartAssert\YamlFile\FileHashes\Deserializer: ~

    SmartAssert\YamlFile\Collection\Deserializer: ~
