imports:
    - { resource: services/test_common.yaml }

parameters:
    compiler_source_directory: '%env(resolve:COMPILER_SOURCE_DIRECTORY)%'
    compiler_target_directory: '%env(resolve:COMPILER_TARGET_DIRECTORY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Services\TestTestMutator:
        public: true

    App\Tests\Services\Asserter\MessengerAsserter:
        public: true
        arguments:
            $transport: '@messenger.transport.async'

    app.tests.services.guzzle.handler.queuing:
        public: true
        class: GuzzleHttp\Handler\MockHandler
        factory: [ '@App\Tests\Services\Guzzle\HandlerFactory', 'createQueuingMockHandler' ]

    GuzzleHttp\HandlerStack:
        factory: [ '@App\Tests\Services\Guzzle\HandlerStackFactory', 'create' ]
        arguments:
            $handler: '@app.tests.services.guzzle.handler.queuing'

    App\Tests\Services\Guzzle\HandlerFactory: ~

    App\Tests\Services\Guzzle\HandlerStackFactory: ~

    App\Tests\Services\Guzzle\ClientFactory: ~

    Psr\Http\Client\ClientInterface:
        class: GuzzleHttp\Client
        factory: [ '@App\Tests\Services\Guzzle\ClientFactory', 'get' ]

    App\Tests\Services\SourceFileInspector:
        public: true
        arguments:
            $path: '%compiler_source_directory%'

    App\Tests\Services\EventRecorder:
        public: true
