name: Emit Repository Dispatch Event

on:
  pull_request:

jobs:
  dispatch:
    name: Emit repository-dispatch event to smartassert/worker-deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get versions from .image-versions.env
        id: dependency-versions
        run: |
          while read line
          do
            key=$(echo $line | cut -d'=' -f1)
            value=$(echo $line | cut -d'=' -f2)
            echo "::set-output name=$key::$value"
          done <<<$(cat .image-versions.env)

      - name: Set app version from release tag
        id: app-version
        env:
          RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}
        run: |
          [[ ! -z "$RELEASE_TAG_NAME" ]] && echo "::set-output name=value::$RELEASE_TAG_NAME" || echo "::set-output name=value::master"

      - name: Examine versions
        run: |
          echo steps.app-version.outputs.value ${{ steps.app-version.outputs.value }}
          echo steps.dependency-versions.outputs.COMPILER_VERSION ${{ steps.dependency-versions.outputs.COMPILER_VERSION }}
          echo steps.dependency-versions.outputs.CHROME_RUNNER_VERSION ${{ steps.dependency-versions.outputs.CHROME_RUNNER_VERSION }}
          echo steps.dependency-versions.outputs.FIREFOX_RUNNER_VERSION ${{ steps.dependency-versions.outputs.FIREFOX_RUNNER_VERSION }}
          echo steps.dependency-versions.outputs.DELEGATOR_VERSION ${{ steps.dependency-versions.outputs.DELEGATOR_VERSION }}

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.WORKER_DEPLOY_TOKEN }}
          repository: smartassert/worker-deploy
          event-type: test
          client-payload: '{"worker_version": "${{ steps.app-version.outputs.value }}", "compiler_version": "${{ steps.dependency-versions.outputs.COMPILER_VERSION }}", "chrome_runner_version": "${{ steps.dependency-versions.outputs.CHROME_RUNNER_VERSION }}", "firefox_runner_version": "${{ steps.dependency-versions.outputs.FIREFOX_RUNNER_VERSION }}", "delegator_version": "${{ steps.dependency-versions.outputs.DELEGATOR_VERSION }}"}'
