name: Emit Repository Dispatch Event

on:
  pull_request:

jobs:
  dispatch:
    name: Emit repository-dispatch event to smartassert/worker-deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Create payload
        id: payload
        run: |
          while read line
          do
            key=$(echo $line | cut -d'=' -f1)
            value=$(echo $line | cut -d'=' -f2)
            echo "::set-output name=$key::$value"
          done <<<$(cat .image-versions.env)

      - name: Examine payload
        run: |
          echo ${{ steps.payload.outputs.COMPILER_VERSION }}
          echo ${{ steps.payload.outputs.CHROME_RUNNER_VERSION }}
          echo ${{ steps.payload.outputs.FIREFOX_RUNNER_VERSION }}
          echo ${{ steps.payload.outputs.DELEGATOR_VERSION }}

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.WORKER_DEPLOY_TOKEN }}
          repository: smartassert/worker-deploy
          event-type: test
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "custom_field": "custom value"}'
