name: tests-integration-image

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  integration-app:
    name: Integration Image - PHP ${{ matrix.php }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php: ['8.1']
    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Run tests
        run: composer test-image
