name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  integration-sync:
    name: Sync integration tests - PHP ${{ matrix.php }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php: ['8.0', '8.1']
    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: pgsql

      - name: Download dependencies
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php }}

      - name: Setup integration test environment
        run: composer integration-setup

      - name: Run tests
        run: composer test-integration

  integration-app:
    name: Image integration tests - PHP ${{ matrix.php }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php: ['8.0', '8.1']
    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: pgsql

      - name: Download dependencies
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php }}

      - name: Setup image test environment
        run: |
          composer integration-setup
          composer image-start
          sleep 5
          composer image-chown-app-source

      - name: Run tests
        run: composer test-image
