name: tests-integration-image

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      test_names: ${{ env.test_names }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set test names
        id: test_names
        run: |
          TEST_NAMES=$(ls tests/Image --ignore=Abstract*)
          TEST_NAMES_LACKING_EXTENSION="${TEST_NAMES//.php/}"          
          TEST_NAMES_AS_JSON_ARRAY=$(jq -ncR '[inputs]' <<< "$TEST_NAMES_LACKING_EXTENSION")

          echo "test_names=$TEST_NAMES_AS_JSON_ARRAY" >> "$GITHUB_ENV"

  integration-app:
    name: Integration Image - ${{ matrix.test_name }}
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php: ['8.1']
        test_name: ${{ fromJson(needs.setup.outputs.test_names) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Setup image test environment
        run: |
          composer image-start
          sleep 5
          composer image-chown-app-source

      - name: Run tests
        run: ./vendor/bin/phpunit -c phpunit.integration.xml tests/Image/${{ matrix.test_name }}.php
